# Generated by Django 5.1.7 on 2025-03-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'Estados Unidos'), ('BR', 'Brasil'), ('AR', 'Argentina'), ('MX', 'Mexico'), ('CO', 'Colombia'), ('ES', 'Espanha')], max_length=100, null=True)),
            ],
        ),
    ]
